// #define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
// #define RGBLIGHT_DEFAULT_MODE RGB_MATRIX_MULTISPLASH
// #define RGBLIGHT_DEFAULT_HUE 0

#define AUTO_SHIFT_TIMEOUT 150
#define RGB_MATRIX_SLEEP
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
